### ISSUE TITLE
handling of the add_idx_to_cc function

### ISSUE THREAD

**Issue by JohannesKarwou** [JohannesKarwou/transformato#3]
@agrass15268, Transformato crashes when the order of common core idx list doesn't match. Maybe inserting some sorting in the `s1_to_s2.add_idx_to_cc` might help

**Comment by agrass15268** [comment]
Should be handled satisfactorily in #2 now. `add_idx_to_cc` now writes to an array, which gets sorted and evaluated upon `finish_common_core()` being called.
